import { DetectivePersona } from './types';

/**
 * 真实历史侦探角色库 — 按朝代、国家、年代分类
 * 涵盖古代中国、古代世界、中世纪欧洲、18/19/20 世纪
 * 保留福尔摩斯/柯南作为特例
 */
export const DETECTIVE_PERSONAS: DetectivePersona[] = [
  // ===== 特例保留（经典虚构） =====
  {
    id: 'holmes',
    name: '夏洛克·福尔摩斯',
    nameZh: '夏洛克·福尔摩斯',
    nameEn: 'Sherlock Holmes',
    title: '咨询侦探',
    description: '冷峻的逻辑演绎与非凡的观察力，从细节中揭示真相',
    quote: '排除所有不可能的，剩下的无论多不可思议，都是真相。',
    accentColor: 'text-amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
  },
  {
    id: 'conan',
    name: '江户川柯南',
    nameZh: '江户川柯南',
    nameEn: 'Detective Conan',
    title: '少年名侦探',
    description: '科学推理与现代刑侦技术结合，真相只有一个',
    quote: '真相永远只有一个！',
    accentColor: 'text-blue-600',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },

  // ===== 古代中国 =====
  {
    id: 'digong',
    name: '狄仁杰',
    nameZh: '狄仁杰',
    nameEn: 'Di Renjie',
    title: '大唐名相 · 唐代',
    description: '一年断案一千七百余件无一冤诉，武则天最信任的宰相',
    quote: '法者，天下之公器也。',
    accentColor: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-400',
  },
  {
    id: 'baozheng',
    name: '包拯',
    nameZh: '包拯',
    nameEn: 'Bao Zheng',
    title: '包青天 · 宋代',
    description: '铁面无私的宋代清官，明镜高悬断案如神',
    quote: '清心为治本，直道是身谋。',
    accentColor: 'text-amber-800',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-500',
  },
  {
    id: 'songci',
    name: '宋慈',
    nameZh: '宋慈',
    nameEn: 'Song Ci',
    title: '法医始祖 · 宋代',
    description: '《洗冤集录》作者，世界法医学奠基人',
    quote: '狱事莫重于大辟，大辟莫重于初情。',
    accentColor: 'text-lime-700',
    bgColor: 'bg-lime-50',
    borderColor: 'border-lime-400',
  },
  {
    id: 'hairui',
    name: '海瑞',
    nameZh: '海瑞',
    nameEn: 'Hai Rui',
    title: '海青天 · 明代',
    description: '明代著名清官，以刚正不阿和严惩贪腐著称，敢直接上书批评皇帝',
    quote: '为官一任，造福一方。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-400',
  },
  {
    id: 'kuangzhong',
    name: '况钟',
    nameZh: '况钟',
    nameEn: 'Kuang Zhong',
    title: '况青天 · 明代',
    description: '苏州知府，以公正判案和治理地方闻名，深得百姓拥戴',
    quote: '公正廉明，为民请命。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-400',
  },
  {
    id: 'shishilun',
    name: '施世纶',
    nameZh: '施世纶',
    nameEn: 'Shi Shilun',
    title: '施公 · 清代',
    description: '扬州知府，《施公奇案》原型，从县令升至总督',
    quote: '明镜高悬，公正无私。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-400',
  },

  // ===== 古代世界 =====
  {
    id: 'cicero',
    name: '西塞罗',
    nameZh: '西塞罗',
    nameEn: 'Marcus Tullius Cicero',
    title: '古罗马 · 公元前 106-43',
    description: '古罗马最伟大的演说家和法学家，跨越西西里岛搜集证据起诉贪腐总督维勒斯',
    quote: '真相因时光而愈明。',
    accentColor: 'text-red-800',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'antiphon',
    name: '安提丰',
    nameZh: '安提丰',
    nameEn: 'Antiphon',
    title: '古希腊 · 公元前 480-411',
    description: '古希腊最早的法庭演说家，为谋杀案件撰写辩护和起诉词',
    quote: '正义在于说出真相。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'chanakya',
    name: '考底利耶',
    nameZh: '考底利耶',
    nameEn: 'Chanakya / Kautilya',
    title: '古印度 · 公元前 350-275',
    description: '《政事论》作者，建立了古代最精密的情报和刑事调查体系',
    quote: '暗处的眼睛能看到最明亮的秘密。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'qehsu',
    name: '凯苏',
    nameZh: '凯苏',
    nameEn: 'Qehsu',
    title: '古埃及 · 公元前 1100',
    description: '新王国时期麦德杰警察指挥官，主持了历史上最早记录的盗墓调查',
    quote: '秩序是正义的基础。',
    accentColor: 'text-yellow-600',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-300',
  },

  // ===== 中世纪欧洲 =====
  {
    id: 'lareynie',
    name: '拉·雷尼',
    nameZh: '拉·雷尼',
    nameEn: 'Gabriel Nicolas de la Reynie',
    title: '法国 · 1625-1709',
    description: '巴黎首位警察总监，创建法国现代警察力量，主导著名的投毒案调查',
    quote: '秩序与光明，是城市最好的守护者。',
    accentColor: 'text-sky-700',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-300',
  },
  {
    id: 'desgrez',
    name: '德格列',
    nameZh: '德格列',
    nameEn: 'François Desgrez',
    title: '法国 · 1632-1705',
    description: '巴黎警署副手，擅长卧底调查，是历史上最早的刑侦调查员之一',
    quote: '真相往往藏在你看不见的地方。',
    accentColor: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },

  // ===== 18 世纪 =====
  {
    id: 'hfielding',
    name: '亨利·菲尔丁',
    nameZh: '亨利·菲尔丁',
    nameEn: 'Henry Fielding',
    title: '英国 · 1707-1754',
    description: '创立鲍街跑者（伦敦第一支专业刑侦力量），同时也是著名小说家',
    quote: '正义不仅需要善良的心，更需要敏锐的眼睛。',
    accentColor: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'jfielding',
    name: '约翰·菲尔丁',
    nameZh: '约翰·菲尔丁',
    nameEn: 'Sir John Fielding',
    title: '英国 · 1721-1780',
    description: '"盲人法官"，虽双目失明却继续扩展刑侦系统，创建骑警巡逻队',
    quote: '即使看不见，也能洞察真相。',
    accentColor: 'text-zinc-600',
    bgColor: 'bg-zinc-50',
    borderColor: 'border-zinc-300',
  },

  // ===== 19 世纪欧洲 =====
  {
    id: 'vidocq',
    name: '维多克',
    nameZh: '维多克',
    nameEn: 'Eugène François Vidocq',
    title: '法国 · 1775-1857',
    description: '从罪犯到侦探，创办世界上第一个侦探机构，现代犯罪学之父',
    quote: '要抓住罪犯，你必须先像罪犯一样思考。',
    accentColor: 'text-zinc-600',
    bgColor: 'bg-zinc-50',
    borderColor: 'border-zinc-300',
  },
  {
    id: 'bertillon',
    name: '贝蒂荣',
    nameZh: '贝蒂荣',
    nameEn: 'Alphonse Bertillon',
    title: '法国 · 1853-1914',
    description: '发明人体测量学和罪犯照片系统，刑事鉴识科学先驱',
    quote: '每个人的身体都是独一无二的档案。',
    accentColor: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-300',
  },
  {
    id: 'abberline',
    name: '阿伯林',
    nameZh: '阿伯林',
    nameEn: 'Frederick Abberline',
    title: '英国 · 1843-1929',
    description: '苏格兰场首席督察，主导开膛手杰克案件调查',
    quote: '每座城市都有它最黑暗的秘密。',
    accentColor: 'text-gray-700',
    bgColor: 'bg-gray-50',
    borderColor: 'border-gray-300',
  },
  {
    id: 'gross',
    name: '汉斯·格罗斯',
    nameZh: '汉斯·格罗斯',
    nameEn: 'Hans Gross',
    title: '奥地利 · 1847-1915',
    description: '出版第一部犯罪调查手册，创造"刑事鉴定学"一词，法医心理学奠基人',
    quote: '科学的眼睛，能看到肉眼看不到的东西。',
    accentColor: 'text-violet-700',
    bgColor: 'bg-violet-50',
    borderColor: 'border-violet-300',
  },
  {
    id: 'locard',
    name: '洛卡德',
    nameZh: '洛卡德',
    nameEn: 'Edmond Locard',
    title: '法国 · 1877-1966',
    description: '"法国版福尔摩斯"，建立首个警察实验室，提出"洛卡德交换原理"',
    quote: '每一次接触，都会留下痕迹。',
    accentColor: 'text-rose-700',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
  },

  // ===== 19 世纪美洲 =====
  {
    id: 'pinkerton',
    name: '平克顿',
    nameZh: '平克顿',
    nameEn: 'Allan Pinkerton',
    title: '美国 · 1819-1884',
    description: '创立平克顿侦探事务所，开创卧底行动和罪犯数据库',
    quote: '我们绝不睡觉。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'warne',
    name: '凯特·沃恩',
    nameZh: '凯特·沃恩',
    nameEn: 'Kate Warne',
    title: '美国 · 1833-1868',
    description: '史上第一位女侦探，平克顿侦探社王牌卧底',
    quote: '当男人无法接近的地方，女人可以。',
    accentColor: 'text-pink-700',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
  },

  // ===== 20 世纪 =====
  {
    id: 'spilsbury',
    name: '斯皮尔斯伯里',
    nameZh: '斯皮尔斯伯里',
    nameEn: 'Sir Bernard Spilsbury',
    title: '英国 · 1877-1947',
    description: '英国最著名的法医病理学家，数百起重大谋杀案的法医鉴定',
    quote: '尸体从不说谎。',
    accentColor: 'text-red-800',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'henrylee',
    name: '李昌钰',
    nameZh: '李昌钰',
    nameEn: 'Henry C. Lee',
    title: '美国/华裔 · 1938-',
    description: '世界知名刑事鉴识专家，参与辛普森案等数千起重大案件',
    quote: '让证据说话。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'ness',
    name: '埃利奥特·内斯',
    nameZh: '埃利奥特·内斯',
    nameEn: 'Eliot Ness',
    title: '美国 · 1903-1957',
    description: '率领"铁面无私"小组扳倒黑帮老大阿尔·卡彭',
    quote: '正义需要勇气，更需要坚持。',
    accentColor: 'text-orange-800',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'jeffreys',
    name: '杰弗里斯',
    nameZh: '杰弗里斯',
    nameEn: 'Sir Alec Jeffreys',
    title: '英国 · 1950-',
    description: 'DNA 指纹技术发明者，彻底改变全球刑事鉴定方式',
    quote: '每个人的 DNA 都是一本独特的密码书。',
    accentColor: 'text-purple-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
  },
  {
    id: 'glessnerlee',
    name: '格罗斯纳·李',
    nameZh: '格罗斯纳·李',
    nameEn: 'Frances Glessner Lee',
    title: '美国 · 1878-1962',
    description: '"法医之母"，用微缩犯罪现场模型训练了数代刑事调查员',
    quote: '细节决定真相。',
    accentColor: 'text-rose-800',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
  },
  {
    id: 'burns',
    name: '威廉·伯恩斯',
    nameZh: '威廉·伯恩斯',
    nameEn: 'William J. Burns',
    title: '美国 · 1861-1932',
    description: '"美国版福尔摩斯"，创办国际侦探事务所，后任FBI局长',
    quote: '追踪罪犯需要比他们更聪明。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },

  // ===== 19 世纪欧洲 扩充 =====
  {
    id: 'bell',
    name: '约瑟夫·贝尔',
    nameZh: '约瑟夫·贝尔',
    nameEn: 'Dr. Joseph Bell',
    title: '苏格兰 · 1837-1911',
    description: '爱丁堡大学外科医生，福尔摩斯的主要原型，擅长通过观察细节推断病人职业和病史',
    quote: '观察是最强大的诊断工具。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'galton',
    name: '弗朗西斯·高尔顿',
    nameZh: '弗朗西斯·高尔顿',
    nameEn: 'Sir Francis Galton',
    title: '英国 · 1822-1911',
    description: '指纹分类系统奠基人，为现代指纹学奠定科学基础，达尔文的表弟',
    quote: '每个人的指纹都是上帝刻下的独特签名。',
    accentColor: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'caminada',
    name: '杰罗姆·卡米纳达',
    nameZh: '杰罗姆·卡米纳达',
    nameEn: 'Jerome Caminada',
    title: '英国 · 1844-1914',
    description: '曼彻斯特传奇侦探，"真实福尔摩斯"，将1225名罪犯送入监狱，擅长卧底侦查',
    quote: '罪犯的世界和正常人的世界只有一线之隔。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'wensley',
    name: '弗雷德·温斯利',
    nameZh: '弗雷德·温斯利',
    nameEn: 'Fred Wensley',
    title: '英国 · 1861-1939',
    description: '苏格兰场传奇警探，参与追捕开膛手杰克，后组建伦敦警察厅"飞行小队"',
    quote: '每一座城市的阴影里都藏着最黑暗的秘密。',
    accentColor: 'text-gray-700',
    bgColor: 'bg-gray-50',
    borderColor: 'border-gray-300',
  },
  {
    id: 'clarke',
    name: '乔治·克拉克',
    nameZh: '乔治·克拉克',
    nameEn: 'George Clarke',
    title: '英国 · 19世纪',
    description: '维多利亚时期苏格兰场超级警探，1864年铁路谋杀案是其首个大案',
    quote: '铁轨不会说话，但它会告诉你一切。',
    accentColor: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'pollaky',
    name: '伊格纳修斯·波拉基',
    nameZh: '伊格纳修斯·波拉基',
    nameEn: 'Ignatius Paul Pollaky',
    title: '匈牙利/英国 · 1832-1895',
    description: '伦敦首批著名私家侦探，人称"Paddington Pollaky"，英国私家侦探先驱',
    quote: '当官方无能为力时，私家侦探就要站出来。',
    accentColor: 'text-amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
  },
  {
    id: 'featherstone',
    name: '约翰·费瑟斯通',
    nameZh: '约翰·费瑟斯通',
    nameEn: 'John Featherstone',
    title: '英国 · 19世纪',
    description: '伦敦警察厅早期著名警探，刑事调查开拓者之一',
    quote: '耐心和细致是侦探最好的武器。',
    accentColor: 'text-zinc-600',
    bgColor: 'bg-zinc-50',
    borderColor: 'border-zinc-300',
  },

  // ===== 19 世纪美洲 扩充 =====
  {
    id: 'einstein',
    name: '伊齐·爱因斯坦',
    nameZh: '伊齐·爱因斯坦',
    nameEn: 'Izzy Einstein',
    title: '美国 · 1880-1938',
    description: '禁酒令传奇探员，通过数百种伪装查获数千家非法酒吧，与莫伊·史密斯搭档',
    quote: '好侦探要会伪装，更好的侦探要会享受伪装。',
    accentColor: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'petrosino',
    name: '乔·佩蒂罗斯',
    nameZh: '乔·佩蒂罗斯',
    nameEn: 'Joseph Petrosino',
    title: '意大利/美国 · 1860-1909',
    description: '纽约警局传奇，打击黑手党先行者，"意大利黑手党的克星"',
    quote: '正义没有国界，但罪犯有。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'flynn',
    name: '威廉·J·弗林',
    nameZh: '威廉·J·弗林',
    nameEn: 'William J. Flynn',
    title: '美国 · 1867-1928',
    description: '前美国特勤局局长，联邦调查局早期领导者，以反间谍工作闻名',
    quote: '国家安全建立在每一条线索之上。',
    accentColor: 'text-blue-800',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'chaplain',
    name: '陈阿平',
    nameZh: '陈阿平',
    nameEn: 'Chang Apana',
    title: '美国/华裔 · 1871-1934',
    description: '檀香山华裔探长，著名小说《陈查理》原型人物，以敏锐直觉和坚韧著称',
    quote: '真相不分种族，正义不分国界。',
    accentColor: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-400',
  },
  {
    id: 'goodwin',
    name: '伊莎贝拉·古德温',
    nameZh: '伊莎贝拉·古德温',
    nameEn: 'Isabella Goodwin',
    title: '美国 · 19世纪末-20世纪初',
    description: '纽约第一位女侦探，假扮女佣潜伏调查侦破大案，打破职业天花板',
    quote: '当女人开始侦查，男人才知道什么叫做细致。',
    accentColor: 'text-pink-600',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
  },
  {
    id: 'clement',
    name: '爱丽丝·克莱门特',
    nameZh: '爱丽丝·克莱门特',
    nameEn: 'Alice Clement',
    title: '美国 · 1870-1928',
    description: '芝加哥首位女侦探，化装侦查大师，逮捕超过1500名嫌犯',
    quote: '最好的伪装不是变成另一个人，而是让对方忘记你是谁。',
    accentColor: 'text-fuchsia-700',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-300',
  },
  {
    id: 'west',
    name: '莫德·韦斯特',
    nameZh: '莫德·韦斯特',
    nameEn: 'Maud West',
    title: '英国 · 1865-1953',
    description: '爱德华时代英国著名女侦探，1905年开设自己侦探事务所，伦敦新闻常客',
    quote: '一个女人的眼睛比十个男人的耳朵更能发现秘密。',
    accentColor: 'text-rose-600',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
  },
  {
    id: 'mallory',
    name: '杰克·马洛里',
    nameZh: '杰克·马洛里',
    nameEn: 'Jack Mallory',
    title: '美国 · 19世纪',
    description: '平克顿侦探社著名侦探，以侦破火车大劫案闻名西部',
    quote: '铁轨延伸到哪里，罪恶就延伸到哪里。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'webster',
    name: '韦伯斯特',
    nameZh: '韦伯斯特',
    nameEn: 'D. H. Webster',
    title: '美国 · 19世纪',
    description: '平克顿侦探社著名侦探，追捕西部不法之徒经验丰富',
    quote: '西部的法律，是用靴子和枪写成的。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'schindler',
    name: '雷蒙德·C·辛德勒',
    nameZh: '雷蒙德·C·辛德勒',
    nameEn: 'Raymond C. Schindler',
    title: '美国 · 1882-1957',
    description: '美国早期著名私家侦探，处理多起高调案件，调查工作出色',
    quote: '真相不需要你去找，它自己会浮现。',
    accentColor: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'oconnell_j',
    name: '约翰·J·奥康奈尔',
    nameZh: '约翰·J·奥康奈尔',
    nameEn: 'John J. O\'Connell',
    title: '美国 · 19世纪末-20世纪初',
    description: '平克顿铁路侦探，追捕火车劫匪的开创性工作',
    quote: '火车抢劫犯以为能跑得比法律快，但他们错了。',
    accentColor: 'text-stone-600',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'oconnell_d',
    name: '丹尼尔·J·奥康奈尔',
    nameZh: '丹尼尔·J·奥康奈尔',
    nameEn: 'Daniel J. O\'Connell',
    title: '美国 · 19世纪末-20世纪初',
    description: '平克顿铁路侦探，与约翰搭档追捕火车劫匪',
    quote: '兄弟联手，没有逃犯能走出我们的视线。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },

  // ===== 20 世纪 扩充 =====
  {
    id: 'toschi',
    name: '戴夫·托斯奇',
    nameZh: '戴夫·托斯奇',
    nameEn: 'Dave Toschi',
    title: '美国 · 1931-2018',
    description: '追查十二宫杀手的传奇警探，电影《肮脏的哈里》主角原型',
    quote: '有些罪犯以为自己能逃脱，但我让他们知道什么叫坚持。',
    accentColor: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-400',
  },
  {
    id: 'kenda',
    name: '乔·肯达',
    nameZh: '乔·肯达',
    nameEn: 'Joe Kenda',
    title: '美国 · 1942-',
    description: '退休凶杀案警探，经手387起凶杀案，侦破356起，破案率高达92%',
    quote: '死人不会说话，但他们的身体会告诉你一切。',
    accentColor: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'pistone',
    name: '约瑟夫·皮斯蒂奥内',
    nameZh: '约瑟夫·皮斯蒂奥内',
    nameEn: 'Joseph Pistone',
    title: '美国 · 1939-',
    description: 'FBI传奇卧底，化名"唐尼·布拉斯科"潜入黑手党，经历改编为电影《忠奸人》',
    quote: '在黑手党里，信任是比子弹更危险的武器。',
    accentColor: 'text-gray-800',
    bgColor: 'bg-gray-50',
    borderColor: 'border-gray-300',
  },
  {
    id: 'murphy',
    name: '史蒂夫·墨菲',
    nameZh: '史蒂夫·墨菲',
    nameEn: 'Steve Murphy',
    title: '美国 · 1958-',
    description: '前DEA特工，追捕巴勃罗·埃斯科巴，电视剧《毒枭》原型之一',
    quote: '毒品帝国的倒塌，从第一份情报开始。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-300',
  },
  {
    id: 'pena',
    name: '哈维尔·佩纳',
    nameZh: '哈维尔·佩纳',
    nameEn: 'Javier Peña',
    title: '美国 · 1953-',
    description: '前DEA特工，与墨菲一同追捕埃斯科巴，《毒枭》原型',
    quote: '正义有时迟到，但从不缺席。',
    accentColor: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'serpico',
    name: '弗兰克·塞皮科',
    nameZh: '弗兰克·塞皮科',
    nameEn: 'Frank Serpico',
    title: '美国 · 1936-',
    description: '揭露纽约警局系统性腐败的传奇警探，经历改编为电影《塞尔皮科》',
    quote: '腐败不是一个人的堕落，是整个系统的溃烂。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'hiratsuka',
    name: '平塚八兵衛',
    nameZh: '平塚八兵衛',
    nameEn: 'Heihachiro Hiratsuka',
    title: '日本 · 1894-1975',
    description: '侦破"帝银事件""三亿元事件"等日本犯罪史著名大案的传奇警探',
    quote: '日本的犯罪有自己的逻辑，但真相是全世界通用的。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'koshko',
    name: '阿卡迪·科什科',
    nameZh: '阿卡迪·科什科',
    nameEn: 'Arkadiy Koshko',
    title: '俄罗斯帝国 · 1865-1925',
    description: '俄罗斯帝国顶尖调查员，领导下的俄国警方1913年破案率被认为是欧洲最高',
    quote: '在俄罗斯，侦探不只是找证据，更是解读人心。',
    accentColor: 'text-blue-800',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-400',
  },
  {
    id: 'tofte',
    name: '欧努尔夫·托夫特',
    nameZh: '欧努尔夫·托夫特',
    nameEn: 'Ørnulf Tofte',
    title: '挪威 · 1920-2004',
    description: '挪威著名警官，冷战期间情报界重要人物，参与所有三大间谍案调查',
    quote: '间谍的世界里，真相是最危险的武器。',
    accentColor: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'fabian',
    name: '鲍勃·费边',
    nameZh: '鲍勃·费边',
    nameEn: 'Bob Fabian',
    title: '英国 · 20世纪',
    description: '苏格兰场"飞行小队"负责人，因拆除爱尔兰共和军炸弹获国王警察奖章',
    quote: '勇敢不是不害怕，而是害怕了还要去做。',
    accentColor: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'wickstead',
    name: '伯特·维克斯特德',
    nameZh: '伯特·维克斯特德',
    nameEn: 'Bert Wickstead',
    title: '英国 · 20世纪',
    description: '苏格兰场警探，打击二战后伦敦东区帮派犯罪，人称"捣黑专家"',
    quote: '帮派不是天生的，是环境造就的。但罪犯的选择是他们自己的。',
    accentColor: 'text-slate-700',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'murray',
    name: '约翰·威尔逊·默里',
    nameZh: '约翰·威尔逊·默里',
    nameEn: 'John Wilson Murray',
    title: '加拿大 · 1851-1911',
    description: '"伟大的加拿大侦探"，科学刑侦先驱，最早利用尸检等法医学信息破案',
    quote: '科学是最好的翻译官，它能翻译死人的语言。',
    accentColor: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'tallman',
    name: '哈里·塔普曼',
    nameZh: '哈里·塔普曼',
    nameEn: 'Harry Tallman',
    title: '澳大利亚 · 20世纪',
    description: '澳大利亚传奇警探，破获"格雷姆·索恩绑架谋杀案"',
    quote: '绑架案的关键永远在细节里。',
    accentColor: 'text-amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-300',
  },
  {
    id: 'christie',
    name: '约翰·克里斯蒂',
    nameZh: '约翰·克里斯蒂',
    nameEn: 'John Christie',
    title: '澳大利亚 · 19世纪末-20世纪初',
    description: '"澳大利亚的夏洛克·福尔摩斯"，擅长化装侦查，破获多起走私和谋杀案',
    quote: '最好的侦探是那些能变成任何人的人。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'onraet',
    name: '伦内·翁拉特',
    nameZh: '伦内·翁拉特',
    nameEn: 'René Onraet',
    title: '荷兰/新加坡 · 1889-1972',
    description: '海峡殖民地警察总监，成功打击地区赌博活动，改革刑事侦查部门',
    quote: '改革不是换人，是换制度。',
    accentColor: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },

  // ===== 中国古代 扩充 =====
  {
    id: 'gaoyao',
    name: '皋陶',
    nameZh: '皋陶',
    nameEn: 'Gao Yao',
    title: '上古时期',
    description: '中国司法鼻祖，制定《狱典》，以独角兽"獬豸"决狱，追求"天下无虐刑"',
    quote: '天下无虐刑，世间无冤狱。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'zhaoguanghan',
    name: '赵广汉',
    nameZh: '赵广汉',
    nameEn: 'Zhao Guanghan',
    title: '西汉 · 公元前1世纪',
    description: '发明"缿筩"（古代举报箱），鼓励匿名举报，打击豪强整顿治安',
    quote: '匿名的声音，往往最接近真相。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'huangba',
    name: '黄霸',
    nameZh: '黄霸',
    nameEn: 'Huang Ba',
    title: '西汉',
    description: '擅长"以智取证"，著名的"智断争儿案"是利用心理学断案的典范',
    quote: '智慧胜于刑具，人心自有公道。',
    accentColor: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-400',
  },
  {
    id: 'kouzhun',
    name: '寇准',
    nameZh: '寇准',
    nameEn: 'Kou Zhun',
    title: '北宋',
    description: '曾任开封府判官，善断疑难案件，处理政务果敢明决，被百姓誉为"寇青天"',
    quote: '明断是非，公正如山。',
    accentColor: 'text-lime-700',
    bgColor: 'bg-lime-50',
    borderColor: 'border-lime-400',
  },
  {
    id: 'yuchenglong',
    name: '于成龙',
    nameZh: '于成龙',
    nameEn: 'Yu Chenglong',
    title: '清朝',
    description: '康熙帝誉其为"清官第一"，一生清廉，精于从细节入手，常微服私访',
    quote: '清廉如水，明察秋毫。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-400',
  },
  {
    id: 'xuyougong',
    name: '徐有功',
    nameZh: '徐有功',
    nameEn: 'Xu Yougong',
    title: '唐朝(武周)',
    description: '以死护法，平反冤案数百件，三次被判死罪不改其志，以死守法的法官典范',
    quote: '法不可枉，命不可轻。宁可死，不可冤。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },

  // ===== 中国当代刑侦专家 =====
  {
    id: 'wuguoqing',
    name: '乌国庆',
    nameZh: '乌国庆',
    nameEn: 'Wu Guoqing',
    title: '中国 · 1936-2019',
    description: '"中国当代福尔摩斯"，参与侦破"二王""三张"等几乎所有公安部挂号大案，曾有"一袋咸菜破奇案"传奇',
    quote: '再小的线索，也可能是破案的关键。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'cuidaozhi',
    name: '崔道植',
    nameZh: '崔道植',
    nameEn: 'Cui Daozhi',
    title: '中国 · 1934-',
    description: '中国首席枪弹痕迹鉴定专家，"七一勋章"获得者，凭肉眼识别不同枪支弹道，检验7000余件痕迹物证无一差错',
    quote: '每一颗子弹都有自己的"指纹"。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'chenshixian',
    name: '陈世贤',
    nameZh: '陈世贤',
    nameEn: 'Chen Shixian',
    title: '中国 · 1936-',
    description: '"人体损伤机制及损伤生物力学"学科创始人，让尸体"说话"，"千岛湖惨案"中通过关键尸检改变案件定性',
    quote: '尸体会说话，关键是你听得懂。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'gaotangdou',
    name: '高光斗',
    nameZh: '高光斗',
    nameEn: 'Gao Tangdou',
    title: '中国 · 当代',
    description: '著名爆炸分析专家，参与三十多起特大爆炸案现场勘查，仅凭16块碎片侦破武汉公交车爆炸案',
    quote: '爆炸不是毁灭，而是另一种证据。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'zhangxin',
    name: '张欣',
    nameZh: '张欣',
    nameEn: 'Zhang Xin',
    title: '中国 · 当代',
    description: '模拟画像"神笔马良"，公安部最年轻特邀刑侦专家，经手约11000起案件，通过画像破案超1000起',
    quote: '我能画出凶手长什么样，因为证据就在那模糊的一瞥中。',
    accentColor: 'text-purple-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
  },
  {
    id: 'mayulin',
    name: '马玉林',
    nameZh: '马玉林',
    nameEn: 'Ma Yulin',
    title: '中国 · 1905-1980',
    description: '步法追踪技术鼻祖，不识字却练就"码踪"绝技，能通过足迹推断性别、身高、体态、年龄',
    quote: '脚走过的路，比嘴说过的话更诚实。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'dongyanzhen',
    name: '董艳珍',
    nameZh: '董艳珍',
    nameEn: 'Dong Yanzhen',
    title: '中国 · 当代',
    description: '"足迹女神探"，马玉林传承人，16岁起协警破案，协助破获千余起刑事案件',
    quote: '每一步足迹都在讲述一个故事。',
    accentColor: 'text-pink-700',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
  },
  {
    id: 'linyuhui',
    name: '林宇辉',
    nameZh: '林宇辉',
    nameEn: 'Lin Yuhui',
    title: '中国 · 当代',
    description: '模拟画像专家，根据模糊监控成功绘制章莹颖案嫌犯画像，震惊美国FBI',
    quote: '模糊的影像中，隐藏着清晰的面容。',
    accentColor: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'liuyao',
    name: '刘耀',
    nameZh: '刘耀',
    nameEn: 'Liu Yao',
    title: '中国 · 当代',
    description: '中国法医界首位工程院院士，法医毒物分析领域权威，参与建立我国法医毒物分析体系',
    quote: '毒物不会消失，只会转移。找到它，就找到了真相。',
    accentColor: 'text-red-800',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'congbin',
    name: '丛斌',
    nameZh: '丛斌',
    nameEn: 'Cong Bin',
    title: '中国 · 当代',
    description: '中国工程院院士，法医学及交通医学专家，法医病理学、遗传学成果卓著',
    quote: '死亡是终点，但不是证据的终点。',
    accentColor: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'jiazhiwen',
    name: '贾玉文',
    nameZh: '贾玉文',
    nameEn: 'Jia Yuwen',
    title: '中国 · 当代',
    description: '中国刑警学院教授，"文检泰斗"，笔迹鉴定领域声望极高',
    quote: '每一笔一画，都是写字人的"指纹"。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'zhangjizong',
    name: '张继宗',
    nameZh: '张继宗',
    nameEn: 'Zhang Jizong',
    title: '中国 · 当代',
    description: '法医人类学专家，公安部物证鉴定中心主任法医师，参与甘肃"白银案"等大案侦破',
    quote: '骨骼是最后不会说谎的证据。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'liuliang',
    name: '刘良',
    nameZh: '刘良',
    nameEn: 'Liu Liang',
    title: '中国 · 当代',
    description: '华中科技大学法医系教授，新冠疫情期间主持首例新冠肺炎逝者遗体解剖',
    quote: '每一次解剖都是对生命的最后尊重。',
    accentColor: 'text-blue-600',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'lvdenzhong',
    name: '吕登中',
    nameZh: '吕登中',
    nameEn: 'Lv Dengzhong',
    title: '中国 · 当代',
    description: '痕迹检验专家，长期从事法医和痕迹检验，承办数千件重大疑难案件勘验鉴定',
    quote: '痕迹是凶手留给自己的签名。',
    accentColor: 'text-slate-700',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'xulimin',
    name: '徐利民',
    nameZh: '徐利民',
    nameEn: 'Xu Limin',
    title: '中国 · 当代',
    description: '指纹鉴定专家，对人体指纹有惊人记忆力，曾通过0.1毫米笔迹抖动识破模仿笔迹',
    quote: '指纹可以伪造，但细节骗不了人。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-400',
  },
  {
    id: 'jizongtang',
    name: '季宗棠',
    nameZh: '季宗棠',
    nameEn: 'Ji Zongtang',
    title: '中国 · 当代',
    description: '审讯心理专家，擅长心理博弈突破嫌疑人防线，审理过1000余起刑案',
    quote: '最好的审讯是让嫌疑人自己开口。',
    accentColor: 'text-violet-700',
    bgColor: 'bg-violet-50',
    borderColor: 'border-violet-300',
  },
  {
    id: 'chengrui',
    name: '程锐',
    nameZh: '程锐',
    nameEn: 'Cheng Rui',
    title: '中国 · 当代',
    description: '足迹专家，师从"步法追踪技术"传承人，公安部遴选痕迹专家组成员',
    quote: '足迹是行走的证据，每一步都是身份的证明。',
    accentColor: 'text-amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'wangqingju',
    name: '王清举',
    nameZh: '王清举',
    nameEn: 'Wang Qingju',
    title: '中国 · 当代',
    description: '足迹检验专家，建立"立体足迹计算机自动检验系统"，推动足迹鉴定从经验走向科学',
    quote: '科学的足迹鉴定，让经验变成精确的数据。',
    accentColor: 'text-emerald-600',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'mengxiaoping',
    name: '孟小平',
    nameZh: '孟小平',
    nameEn: 'Meng Xiaoping',
    title: '中国 · 当代',
    description: '全国仅有的3个足迹检验专家之一，受理各类疑难案件1300多起',
    quote: '一千三百个现场，每一个都教会我更仔细地看。',
    accentColor: 'text-lime-700',
    bgColor: 'bg-lime-50',
    borderColor: 'border-lime-400',
  },
  {
    id: 'liushuquan',
    name: '刘树权',
    nameZh: '刘树权',
    nameEn: 'Liu Shuquan',
    title: '中国 · 当代',
    description: '足迹检验专家，运用足迹动力学研究成果破获多起重大案件，两次获全国公安系统二级英雄模范',
    quote: '脚步的动力学，藏着凶手的习惯。',
    accentColor: 'text-teal-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'qianghui',
    name: '强辉',
    nameZh: '强辉',
    nameEn: 'Qiang Hui',
    title: '中国 · 当代',
    description: '安徽省公安厅唯一画像师，模拟画像专家',
    quote: '一张模糊的脸，也能被还原成清晰的证据。',
    accentColor: 'text-fuchsia-700',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-300',
  },
  {
    id: 'linqing',
    name: '林清',
    nameZh: '林清',
    nameEn: 'Lin Qing',
    title: '中国 · 当代',
    description: '模拟画像专家，师从"中国首席模拟画像专家"张欣',
    quote: '师傅教我：画的是脸，看的是证据。',
    accentColor: 'text-rose-600',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
  },
  {
    id: 'koujianping',
    name: '寇建平',
    nameZh: '寇建平',
    nameEn: 'Kou Jianping',
    title: '中国 · 当代',
    description: '江苏省常州市公安局刑警，模拟画像专家，曾参与"梅姨"画像绘制',
    quote: '画一张像，可能需要上百次修改，但真相值得。',
    accentColor: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'yuxinmin',
    name: '余新民',
    nameZh: '余新民',
    nameEn: 'Yu Xinmin',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，中国刑事警察学院原党委书记，擅长犯罪心理分析',
    quote: '了解罪犯怎么想，就知道他会怎么做。',
    accentColor: 'text-slate-700',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'yanzizhong',
    name: '闫子忠',
    nameZh: '闫子忠',
    nameEn: 'Yan Zizhong',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，1999年首批获聘的9名专家之一',
    quote: '专业就是能在别人看不到的地方找到线索。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'baishaokang',
    name: '白少康',
    nameZh: '白少康',
    nameEn: 'Bai Shaokang',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，曾任公安部刑侦局局长，参与侦破"华南虎照"等重大案件',
    quote: '大案无小事，细节定成败。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'wangguiqiang',
    name: '王桂强',
    nameZh: '王桂强',
    nameEn: 'Wang Guiqiang',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，长期从事物证光学检验和物证鉴定理论研究，曾任公安部物证鉴定中心副主任',
    quote: '光学能看到的，远超人眼。',
    accentColor: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'minjianxiong',
    name: '闵建雄',
    nameZh: '闵建雄',
    nameEn: 'Min Jianxiong',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，法医损伤学及法医影像学专家',
    quote: '影像不会撒谎，关键在于如何解读。',
    accentColor: 'text-purple-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
  },
  {
    id: 'liujianjun',
    name: '刘建军',
    nameZh: '刘建军',
    nameEn: 'Liu Jianjun',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，声纹鉴定专家，中国语音识别与声纹鉴定领域开创者之一',
    quote: '每个人的声音都有独特的"指纹"。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'banmaosen',
    name: '班茂森',
    nameZh: '班茂森',
    nameEn: 'Ban Maosen',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，微量物证专家，善于通过极其细微的物证锁定嫌疑人',
    quote: '再微小的证据，也可能推翻整个案子。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'wangshiqing',
    name: '王式庆',
    nameZh: '王式庆',
    nameEn: 'Wang Shiqing',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，足迹检验专家，师从马玉林，将现代科技与传统步法追踪结合',
    quote: '老技术加新科技，让足迹鉴定更精确。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-400',
  },
  {
    id: 'zhangshaoqing',
    name: '张绍清',
    nameZh: '张绍清',
    nameEn: 'Zhang Shaoqing',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，文件检验专家，善于从笔迹、印章等文件物证中发现破案线索',
    quote: '一份文件，可能比目击者更诚实。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'wangyanji',
    name: '王彦吉',
    nameZh: '王彦吉',
    nameEn: 'Wang Yanji',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，理化检验专家，中国人民公安大学原校长，毒物毒品分析领域权威',
    quote: '化学分析是物证的核心。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'zhouyunbiao',
    name: '周云彪',
    nameZh: '周云彪',
    nameEn: 'Zhou Yunbiao',
    title: '中国 · 当代',
    description: '公安部特邀刑侦专家，指纹鉴定专家，指纹自动识别系统建设贡献卓著',
    quote: '自动识别让效率提升，但判断力来自经验。',
    accentColor: 'text-blue-600',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'chenlin',
    name: '陈林',
    nameZh: '陈林',
    nameEn: 'Chen Lin',
    title: '中国 · 当代',
    description: '安徽省公安厅物证鉴定管理处副处长，全国公安系统二级英雄模范，利用法医技术屡破奇案',
    quote: '法医不仅是技术活，更是对正义的坚守。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'gaozhanguo',
    name: '高占国',
    nameZh: '高占国',
    nameEn: 'Gao Zhanguo',
    title: '中国 · 当代',
    description: '弹道痕迹检验专家，利用"枪弹痕迹自动识别系统"破获多起特大涉枪案件',
    quote: '每把枪都有自己的"笔迹"。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'wanlihua',
    name: '万立华',
    nameZh: '万立华',
    nameEn: 'Wan Lihua',
    title: '中国 · 当代',
    description: '重庆医科大学原副校长，著名法医学专家，法医现场勘查和死因鉴定经验丰富',
    quote: '现场是最好的课堂，死者是最好的老师。',
    accentColor: 'text-zinc-700',
    bgColor: 'bg-zinc-50',
    borderColor: 'border-zinc-300',
  },

  // ===== 21世纪刑事鉴识 =====
  {
    id: 'reichs',
    name: '凯西·莱克斯',
    nameZh: '凯西·莱克斯',
    nameEn: 'Kathy Reichs',
    title: '美国 · 1948-',
    description: '著名法医人类学家，畅销书作家，《识骨寻踪》主角原型，将法医学推向大众视野',
    quote: '骨头不仅会说话，它们讲述的是最真实的故事。',
    accentColor: 'text-rose-700',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
  },
  {
    id: 'kayser',
    name: '曼弗雷德·凯瑟',
    nameZh: '曼弗雷德·凯瑟',
    nameEn: 'Manfred Kayser',
    title: '荷兰 · 当代',
    description: '法医分子生物学顶尖学者，DNA表型描绘领域权威，能从DNA推断发色、眼睛颜色',
    quote: 'DNA不只是识别你是谁，还能告诉别人你长什么样。',
    accentColor: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'thali',
    name: '迈克尔·J·泰利',
    nameZh: '迈克尔·J·泰利',
    nameEn: 'Michael J. Thali',
    title: '瑞士 · 当代',
    description: '法医影像学先驱，推动"虚拟尸检"技术，利用CT、MRI进行无损尸检',
    quote: '不需要刀，也能看到身体最深处的秘密。',
    accentColor: 'text-cyan-600',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'byard',
    name: '罗杰·拜亚德',
    nameZh: '罗杰·拜亚德',
    nameEn: 'Roger Byard',
    title: '澳大利亚 · 当代',
    description: '法医病理学领军人物，婴儿猝死综合征研究权威，斯坦福全球法医学排名前二',
    quote: '最安静的死亡，往往需要最大的关注。',
    accentColor: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'ubelaker',
    name: '道格·尤贝拉克',
    nameZh: '道格·尤贝拉克',
    nameEn: 'Doug Ubelaker',
    title: '美国 · 当代',
    description: '史密森尼学会高级法医人类学家，骨骼分析和身份鉴定权威',
    quote: '每一块骨头都是一本被遗忘的历史。',
    accentColor: 'text-amber-600',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'aschheim',
    name: '肯尼斯·阿什海姆',
    nameZh: '肯尼斯·阿什海姆',
    nameEn: 'Kenneth Aschheim',
    title: '美国 · 当代',
    description: '美国法医牙科学会认证专家，纽约市首席法医牙科专家，重大灾难牙齿比对身份识别',
    quote: '牙齿是身体最坚硬的部分，也是最后被摧毁的证据。',
    accentColor: 'text-teal-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'acharya',
    name: '阿什斯·B·阿查里亚',
    nameZh: '阿什斯·B·阿查里亚',
    nameEn: 'Ashith B. Acharya',
    title: '印度 · 当代',
    description: '国际知名法医牙科学家，牙齿年龄评估和身份鉴定贡献突出，全球引用率极高',
    quote: '每个人的牙齿都是独一无二的身份证明。',
    accentColor: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },

  // ===== 21世纪犯罪心理 =====
  {
    id: 'douglas',
    name: '约翰·道格拉斯',
    nameZh: '约翰·道格拉斯',
    nameEn: 'John Douglas',
    title: '美国 · 1945-',
    description: 'FBI行为科学调查支援科创始人，现代犯罪心理画像开创者，《沉默的羔羊》专业顾问',
    quote: '要理解犯罪，你必须先进入罪犯的头脑。',
    accentColor: 'text-gray-800',
    bgColor: 'bg-gray-50',
    borderColor: 'border-gray-300',
  },
  {
    id: 'rossmo',
    name: '金·罗斯莫',
    nameZh: '金·罗斯莫',
    nameEn: 'Kim Rossmo',
    title: '美国 · 当代',
    description: '地理画像创立者，"罗斯莫公式"辅助追踪连环犯罪者，空间犯罪学先驱',
    quote: '每个罪犯都有自己的"舒适区"。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'burgess',
    name: '安·伯吉斯',
    nameZh: '安·伯吉斯',
    nameEn: 'Ann Burgess',
    title: '美国 · 当代',
    description: '波士顿学院教授，与FBI合作开创犯罪心理学，奠定现代FBI人质谈判和侧写基础',
    quote: '理解受害者和加害者的关系，是理解犯罪的钥匙。',
    accentColor: 'text-purple-600',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
  },
  {
    id: 'holes',
    name: '保罗·霍尔斯',
    nameZh: '保罗·霍尔斯',
    nameEn: 'Paul Holes',
    title: '美国 · 当代',
    description: '加州悬案调查员，利用DNA族谱学锁定"金州杀手"，数十年追踪终获正义',
    quote: '有些案子可以等，但受害者不能。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'delisi',
    name: '马特·德利西',
    nameZh: '马特·德利西',
    nameEn: 'Matt DeLisi',
    title: '美国 · 当代',
    description: '爱荷华州立大学教授，全球最高产犯罪学家之一，严重暴力和精神错乱犯罪者研究权威',
    quote: '犯罪学的意义不只是理解罪犯，而是预防下一个。',
    accentColor: 'text-slate-700',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'raine',
    name: '艾德里安·雷恩',
    nameZh: '艾德里安·雷恩',
    nameEn: 'Adrian Raine',
    title: '英国 · 当代',
    description: '神经犯罪学领军人物，通过脑成像研究反社会行为和暴力犯罪者生理基础',
    quote: '犯罪不只是选择问题，有时是大脑的问题。',
    accentColor: 'text-fuchsia-700',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-300',
  },
  {
    id: 'kwonilyong',
    name: '权日勇',
    nameZh: '权日勇',
    nameEn: 'Kwon Il-yong',
    title: '韩国 · 当代',
    description: '韩国首位犯罪侧写师，开创韩国犯罪心理分析先河，参与侦破多起连环杀人案',
    quote: '韩国的犯罪有自己的特点，但人性是相通的。',
    accentColor: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'leejinsuk',
    name: '李珍淑',
    nameZh: '李珍淑',
    nameEn: 'Lee Jin-sook',
    title: '韩国 · 当代',
    description: '韩国首位女性犯罪侧写师，从业16年，擅长通过心理分析协助侦破重大刑事案件',
    quote: '女性的直觉在犯罪侧写中是一种超能力。',
    accentColor: 'text-pink-600',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
  },

  // ===== 21世纪现代警务 =====
  {
    id: 'sherman',
    name: '劳伦斯·舍曼',
    nameZh: '劳伦斯·舍曼',
    nameEn: 'Lawrence Sherman',
    title: '英国/美国 · 当代',
    description: '"循证警务"之父，全球警务研究权威，伦敦大都会警察局首位首席科学官',
    quote: '好的警务应该建立在证据上，而不是传统上。',
    accentColor: 'text-blue-800',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'oconnell_m',
    name: '迈克尔·欧·康奈尔',
    nameZh: '迈克尔·欧·康奈尔',
    nameEn: "Michael O'Connell",
    title: '英国 · 当代',
    description: '前国际刑警组织行动警务处主任，联合国犯罪司法所高级执法专家，全球打击网络犯罪领导者',
    quote: '网络犯罪没有国界，我们的回应也不能有边界。',
    accentColor: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'leblanc',
    name: '金罗斯·勒布朗',
    nameZh: '金罗斯·勒布朗',
    nameEn: 'Kingross Leblanc',
    title: '加拿大 · 当代',
    description: '网络犯罪调查专家，打击暗网和加密货币犯罪领域经验丰富',
    quote: '暗网不是法外之地，加密货币也不是。',
    accentColor: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
  },
  {
    id: 'sella',
    name: '安德烈娅·塞拉',
    nameZh: '安德烈娅·塞拉',
    nameEn: 'Andrea Sella',
    title: '英国 · 当代',
    description: '伦敦大学学院化学教授，科学顾问协助破解多起涉及罕见化学物质的悬案',
    quote: '化学反应从不撒谎。',
    accentColor: 'text-teal-600',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'khan',
    name: '卡姆兰·汗',
    nameZh: '卡姆兰·汗',
    nameEn: 'Kamran Khan',
    title: '巴基斯坦 · 当代',
    description: '国际刑警组织专家，打击跨国恐怖主义和有组织犯罪情报分析贡献卓越',
    quote: '恐怖主义是全世界共同的敌人，情报是最好的武器。',
    accentColor: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-400',
  },
  {
    id: 'blumenthal',
    name: '瑞安·布卢门撒尔',
    nameZh: '瑞安·布卢门撒尔',
    nameEn: 'Ryan Blumenthal',
    title: '南非 · 当代',
    description: '资深法医病理学教授，畅销书《解剖》作者，知名科学传播者',
    quote: '让公众理解法医学，就是让社会更接近正义。',
    accentColor: 'text-orange-600',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'weisburd',
    name: '大卫·韦斯伯德',
    nameZh: '大卫·韦斯伯德',
    nameEn: 'David Weisburd',
    title: '以色列/美国 · 当代',
    description: '杰出犯罪学家，警务有效性、犯罪场所研究和白领犯罪领域享有盛名',
    quote: '犯罪不是随机发生的，它有自己的地理学。',
    accentColor: 'text-violet-700',
    bgColor: 'bg-violet-50',
    borderColor: 'border-violet-300',
  },
  {
    id: 'bull',
    name: '雷·布尔',
    nameZh: '雷·布尔',
    nameEn: 'Ray Bull',
    title: '英国 · 当代',
    description: '审讯心理学世界级权威，审讯技巧、证人证词可靠性研究深入',
    quote: '一个好的审讯不是让嫌疑人认罪，而是让他说出真相。',
    accentColor: 'text-stone-700',
    bgColor: 'bg-stone-50',
    borderColor: 'border-stone-300',
  },
  {
    id: 'hagan',
    name: '约翰·L·哈根',
    nameZh: '约翰·L·哈根',
    nameEn: 'John L. Hagan',
    title: '美国 · 当代',
    description: '西北大学教授，犯罪学、法律和社会学领域深远影响，战争罪行和青少年犯罪研究',
    quote: '犯罪的根源，往往在社会结构里。',
    accentColor: 'text-zinc-700',
    bgColor: 'bg-zinc-50',
    borderColor: 'border-zinc-300',
  },
  {
    id: 'pollanen',
    name: '迈克尔·波拉宁',
    nameZh: '迈克尔·波拉宁',
    nameEn: 'Michael Pollanen',
    title: '加拿大 · 当代',
    description: '法医病理学家，国际刑事法庭工作，参与调查战争罪和反人类罪案件',
    quote: '战争罪行的证据，刻在每一个受害者的身体上。',
    accentColor: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'eckert',
    name: '威廉·G·埃克特',
    nameZh: '威廉·G·埃克特',
    nameEn: 'William G. Eckert',
    title: '美国 · 当代',
    description: '现代法医科学组织者和推广者，创办INFORMS为全球法医信息交流奠定基础',
    quote: '知识共享是推动法医学进步的关键。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },

  // ===== 21世纪私家侦探 =====
  {
    id: 'kroll',
    name: '朱尔斯·克罗尔',
    nameZh: '朱尔斯·克罗尔',
    nameEn: 'Jules Kroll',
    title: '美国 · 当代',
    description: '全球最大风险咨询公司克罗尔创始人，"华尔街侦探"，开创现代企业风险调查行业',
    quote: '企业世界的真相，藏在财务报表的背后。',
    accentColor: 'text-emerald-700',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-300',
  },
  {
    id: 'joseph',
    name: '布赖恩·约瑟夫',
    nameZh: '布赖恩·约瑟夫',
    nameEn: 'Brianne Joseph',
    title: '美国 · 当代',
    description: '女性私家侦探，15年以上调查经验，专注网络诈骗调查，经历被Netflix拍成纪录片',
    quote: '网络诈骗的每一个链接，都是追踪的起点。',
    accentColor: 'text-fuchsia-600',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-300',
  },
  {
    id: 'zhangyufen',
    name: '张玉芬',
    nameZh: '张玉芬',
    nameEn: 'Zhang Yufen',
    title: '中国 · 当代',
    description: '中国知名私家侦探，专注婚姻家庭类调查引发社会广泛讨论，"中国第一女子侦探"',
    quote: '婚姻里的真相，有时比犯罪更伤人。',
    accentColor: 'text-pink-600',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-300',
  },

  // ===== 21世纪新兴力量 =====
  {
    id: 'mcnamara',
    name: '米歇尔·麦克纳马拉',
    nameZh: '米歇尔·麦克纳马拉',
    nameEn: 'Michelle McNamara',
    title: '美国 · 1967-2016',
    description: '犯罪作家，创立"True Crime Diary"网站，利用网络和民间力量追踪"金州杀手"十年',
    quote: '有时候，真相不在警方手里，而在普通人眼中。',
    accentColor: 'text-blue-600',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
  {
    id: 'jensen',
    name: '比利·詹森',
    nameZh: '比利·詹森',
    nameEn: 'Billy Jensen',
    title: '美国 · 当代',
    description: '调查记者，DNA族谱学和众包调查应用于悬案的推动者，协助破获"金州杀手"等多起悬案',
    quote: '众包的力量在于，每一双眼睛都可能看到不一样的东西。',
    accentColor: 'text-indigo-600',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
  },
  {
    id: 'weihua',
    name: '魏华',
    nameZh: '魏华',
    nameEn: 'Wei Hua',
    title: '中国 · 当代',
    description: '中国知名调查记者，以团队深度揭露社会黑暗面，推动社会公正',
    quote: '记者的调查笔，也是正义的武器。',
    accentColor: 'text-red-600',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
  },
  {
    id: 'davies',
    name: '尼克·戴维斯',
    nameZh: '尼克·戴维斯',
    nameEn: 'Nick Davies',
    title: '英国 · 当代',
    description: '《卫报》资深调查记者，持续揭露《世界新闻报》窃听丑闻获广泛关注',
    quote: '新闻自由的核心，是揭露真相的勇气。',
    accentColor: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
  },
  {
    id: 'leopold',
    name: '杰森·利奥波德',
    nameZh: '杰森·利奥波德',
    nameEn: 'Jason Leopold',
    title: '美国 · 当代',
    description: '彭博社高级调查记者，熟练运用《信息自由法》申请公开记录，迫使政府披露机密信息',
    quote: '信息公开法是最好的调查工具。',
    accentColor: 'text-green-600',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-300',
  },

  // ===== 中东/非洲/南亚传奇 =====
  {
    id: 'abbakyari',
    name: '阿巴·凯亚里',
    nameZh: '阿巴·凯亚里',
    nameEn: 'Abba Kyari',
    title: '尼日利亚 · 当代',
    description: '尼日利亚警察总监情报响应队负责人，破获多起重大绑架和诈骗案，"非洲最佳侦探"',
    quote: '在非洲，侦探需要的不只是智慧，还有勇气。',
    accentColor: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-400',
  },
  {
    id: 'rashidalghafri',
    name: '拉希德·阿尔加夫里',
    nameZh: '拉希德·阿尔加夫里',
    nameEn: 'Rashid Alghafri',
    title: '阿联酋 · 当代',
    description: '阿联酋著名法医专家，中东地区法医物证领域领军人物，监督处理上万件复杂案件',
    quote: '沙漠中的正义，也需要科学的支撑。',
    accentColor: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
  },
  {
    id: 'hadialghafli',
    name: '哈迪·阿尔·加夫里',
    nameZh: '哈迪·阿尔·加夫里',
    nameEn: 'Hadi Al Ghafli',
    title: '阿联酋 · 当代',
    description: '贝都因部落精英追踪者，卓越智慧和敏锐观察力追捕罪犯逃犯，"沙漠的夏洛克"',
    quote: '沙漠教会我一件事：再小的足迹也能追踪。',
    accentColor: 'text-amber-700',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-400',
  },
  {
    id: 'ramanujghosh',
    name: '拉曼舒·高希',
    nameZh: '拉曼舒·高希',
    nameEn: 'Ramanuj Ghosh',
    title: '印度 · 当代',
    description: '孟买刑事调查局传奇警探，敏锐洞察力和高超破案能力，"孟买神探"',
    quote: '在孟买的喧嚣中，罪恶的声音反而最清晰。',
    accentColor: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
  },
  {
    id: 'johnkai',
    name: '凯约翰',
    nameZh: '凯约翰',
    nameEn: 'John Kai',
    title: '美国/华裔 · 当代',
    description: '纽约第一位亚裔警探，纽约亚裔罪案组高级警官，为破获亚裔悬案做出重要贡献',
    quote: '文化理解是最好的破案工具。',
    accentColor: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
  },
];

/** 按侦探 ID 快速查找 */
export const PERSONA_MAP = DETECTIVE_PERSONAS.reduce(
  (acc, p) => {
    acc[p.id] = p;
    return acc;
  },
  {} as Record<string, DetectivePersona>,
);
