import { DetectiveId } from '@/lib/types';

/* 基础提示词 */
import { BASE_PROMPT } from './base';
export { BASE_PROMPT } from './base';

/* 经典特例 */
import { HOLMES_SYSTEM_PROMPT } from './holmes';
export { HOLMES_SYSTEM_PROMPT } from './holmes';
import { CONAN_SYSTEM_PROMPT } from './asian';
export { CONAN_SYSTEM_PROMPT } from './asian';

/* 中国古代名探 */
import { DIGONG_SYSTEM_PROMPT, BAOZHENG_SYSTEM_PROMPT, SONGCI_SYSTEM_PROMPT } from './chinese';
export { DIGONG_SYSTEM_PROMPT, BAOZHENG_SYSTEM_PROMPT, SONGCI_SYSTEM_PROMPT } from './chinese';
import { HAIRUI_SYSTEM_PROMPT, KUANGZHONG_SYSTEM_PROMPT, SHISHILUN_SYSTEM_PROMPT } from './chinese-extra';
export { HAIRUI_SYSTEM_PROMPT, KUANGZHONG_SYSTEM_PROMPT, SHISHILUN_SYSTEM_PROMPT } from './chinese-extra';

/* 中国古代扩充 */
import {
  GAOTAO_SYSTEM_PROMPT, ZHAOGUANGHAN_SYSTEM_PROMPT, HUANGBA_SYSTEM_PROMPT,
  KOUZHUN_SYSTEM_PROMPT, YUCHENGLONG_SYSTEM_PROMPT, XUYOUGONG_SYSTEM_PROMPT,
} from './historical-extra';
export { GAOTAO_SYSTEM_PROMPT, ZHAOGUANGHAN_SYSTEM_PROMPT, HUANGBA_SYSTEM_PROMPT,
  KOUZHUN_SYSTEM_PROMPT, YUCHENGLONG_SYSTEM_PROMPT, XUYOUGONG_SYSTEM_PROMPT,
} from './historical-extra';

/* 古代世界 */
import { CICERO_SYSTEM_PROMPT, ANTIPHON_SYSTEM_PROMPT, CHANAKYA_SYSTEM_PROMPT, QEHSU_SYSTEM_PROMPT } from './ancient';
export { CICERO_SYSTEM_PROMPT, ANTIPHON_SYSTEM_PROMPT, CHANAKYA_SYSTEM_PROMPT, QEHSU_SYSTEM_PROMPT } from './ancient';

/* 中世纪欧洲 + 18世纪 */
import { LAREYNIE_SYSTEM_PROMPT, DESGREZ_SYSTEM_PROMPT, HFIELDING_SYSTEM_PROMPT, JFIELDING_SYSTEM_PROMPT } from './medieval';
export { LAREYNIE_SYSTEM_PROMPT, DESGREZ_SYSTEM_PROMPT, HFIELDING_SYSTEM_PROMPT, JFIELDING_SYSTEM_PROMPT } from './medieval';

/* 19世纪欧洲 + 扩充 */
import { VIDOCQ_SYSTEM_PROMPT } from './others';
export { VIDOCQ_SYSTEM_PROMPT } from './others';
import { BERTILLON_SYSTEM_PROMPT, ABERLINE_SYSTEM_PROMPT, GROSS_SYSTEM_PROMPT, LOCARD_SYSTEM_PROMPT } from './c19-europe';
export { BERTILLON_SYSTEM_PROMPT, ABERLINE_SYSTEM_PROMPT, GROSS_SYSTEM_PROMPT, LOCARD_SYSTEM_PROMPT } from './c19-europe';
import {
  BELL_SYSTEM_PROMPT, GALTON_SYSTEM_PROMPT, CAMINADA_SYSTEM_PROMPT,
  WENSLEY_SYSTEM_PROMPT, CLARKE_SYSTEM_PROMPT, POLLAKY_SYSTEM_PROMPT, FEATHERSTONE_SYSTEM_PROMPT,
} from './historical-extra';
export { BELL_SYSTEM_PROMPT, GALTON_SYSTEM_PROMPT, CAMINADA_SYSTEM_PROMPT,
  WENSLEY_SYSTEM_PROMPT, CLARKE_SYSTEM_PROMPT, POLLAKY_SYSTEM_PROMPT, FEATHERSTONE_SYSTEM_PROMPT,
} from './historical-extra';

/* 19世纪美洲 + 扩充 */
import { PINKERTON_SYSTEM_PROMPT, WARNE_SYSTEM_PROMPT } from './c19-america';
export { PINKERTON_SYSTEM_PROMPT, WARNE_SYSTEM_PROMPT } from './c19-america';
import {
  EINSTEIN_SYSTEM_PROMPT, PETROSINO_SYSTEM_PROMPT, FLYNN_SYSTEM_PROMPT,
  CHAPLAIN_SYSTEM_PROMPT, GOODWIN_SYSTEM_PROMPT, CLEMENT_SYSTEM_PROMPT, WEST_SYSTEM_PROMPT,
  MALLORY_SYSTEM_PROMPT, WEBSTER_SYSTEM_PROMPT, SCHINDLER_SYSTEM_PROMPT,
  OCONNELL_J_SYSTEM_PROMPT, OCONNELL_D_SYSTEM_PROMPT,
} from './historical-extra';
export { EINSTEIN_SYSTEM_PROMPT, PETROSINO_SYSTEM_PROMPT, FLYNN_SYSTEM_PROMPT,
  CHAPLAIN_SYSTEM_PROMPT, GOODWIN_SYSTEM_PROMPT, CLEMENT_SYSTEM_PROMPT, WEST_SYSTEM_PROMPT,
  MALLORY_SYSTEM_PROMPT, WEBSTER_SYSTEM_PROMPT, SCHINDLER_SYSTEM_PROMPT,
  OCONNELL_J_SYSTEM_PROMPT, OCONNELL_D_SYSTEM_PROMPT,
} from './historical-extra';

/* 20世纪 + 扩充 */
import {
  SPILSBURY_SYSTEM_PROMPT, HENRYLEE_SYSTEM_PROMPT, NESS_SYSTEM_PROMPT,
  JEFFREYS_SYSTEM_PROMPT, GLESSNERLEE_SYSTEM_PROMPT, BURNS_SYSTEM_PROMPT,
} from './c20';
export { SPILSBURY_SYSTEM_PROMPT, HENRYLEE_SYSTEM_PROMPT, NESS_SYSTEM_PROMPT,
  JEFFREYS_SYSTEM_PROMPT, GLESSNERLEE_SYSTEM_PROMPT, BURNS_SYSTEM_PROMPT,
} from './c20';
import {
  TOSCHI_SYSTEM_PROMPT, KENDA_SYSTEM_PROMPT, PISTONE_SYSTEM_PROMPT,
  MURPHY_SYSTEM_PROMPT, PENA_SYSTEM_PROMPT, SERPICO_SYSTEM_PROMPT,
  HIRATSUKA_SYSTEM_PROMPT, KOSHKO_SYSTEM_PROMPT, TOFTE_SYSTEM_PROMPT,
  FABIAN_SYSTEM_PROMPT, WICKSTEAD_SYSTEM_PROMPT, MURRAY_SYSTEM_PROMPT,
  TALLMAN_SYSTEM_PROMPT, CHRISTIE_SYSTEM_PROMPT, ONRAET_SYSTEM_PROMPT,
} from './historical-extra';
export { TOSCHI_SYSTEM_PROMPT, KENDA_SYSTEM_PROMPT, PISTONE_SYSTEM_PROMPT,
  MURPHY_SYSTEM_PROMPT, PENA_SYSTEM_PROMPT, SERPICO_SYSTEM_PROMPT,
  HIRATSUKA_SYSTEM_PROMPT, KOSHKO_SYSTEM_PROMPT, TOFTE_SYSTEM_PROMPT,
  FABIAN_SYSTEM_PROMPT, WICKSTEAD_SYSTEM_PROMPT, MURRAY_SYSTEM_PROMPT,
  TALLMAN_SYSTEM_PROMPT, CHRISTIE_SYSTEM_PROMPT, ONRAET_SYSTEM_PROMPT,
} from './historical-extra';

/* 中国当代刑侦专家 */
import {
  WUGUOQING_SYSTEM_PROMPT, CUIDAOZHI_SYSTEM_PROMPT, CHENSHIXIAN_SYSTEM_PROMPT,
  GAOTANGDOU_SYSTEM_PROMPT, ZHANGXIN_SYSTEM_PROMPT, MAYULIN_SYSTEM_PROMPT,
  DONGYANZHEN_SYSTEM_PROMPT, LINYUHUI_SYSTEM_PROMPT, LIUYAO_SYSTEM_PROMPT,
  CONGBIN_SYSTEM_PROMPT, JIAZHIWEN_SYSTEM_PROMPT, ZHANGJIZONG_SYSTEM_PROMPT,
  LIULIANG_SYSTEM_PROMPT, LVDENZHONG_SYSTEM_PROMPT, XULIMIN_SYSTEM_PROMPT,
  JIZONGTANG_SYSTEM_PROMPT, CHENGRUI_SYSTEM_PROMPT, WANGQINGJU_SYSTEM_PROMPT,
  MENGXIAOPING_SYSTEM_PROMPT, LIUSHUQUAN_SYSTEM_PROMPT, QIANGHUI_SYSTEM_PROMPT,
  LINQING_SYSTEM_PROMPT, KOUJIANPING_SYSTEM_PROMPT, YUXINMIN_SYSTEM_PROMPT,
  YANZIZHONG_SYSTEM_PROMPT, BAISHAOKANG_SYSTEM_PROMPT, WANGGUIQIANG_SYSTEM_PROMPT,
  MINJIANXIONG_SYSTEM_PROMPT, LIUJIANJUN_SYSTEM_PROMPT, BANMAOSEN_SYSTEM_PROMPT,
  WANGSHIQING_SYSTEM_PROMPT, ZHANGSHAOQING_SYSTEM_PROMPT, WANGYANJI_SYSTEM_PROMPT,
  ZHOUYUNBIAO_SYSTEM_PROMPT, CHENLIN_SYSTEM_PROMPT, GAOZHANGUO_SYSTEM_PROMPT,
  WANLIHUA_SYSTEM_PROMPT,
} from './chinese-experts';
export {
  WUGUOQING_SYSTEM_PROMPT, CUIDAOZHI_SYSTEM_PROMPT, CHENSHIXIAN_SYSTEM_PROMPT,
  GAOTANGDOU_SYSTEM_PROMPT, ZHANGXIN_SYSTEM_PROMPT, MAYULIN_SYSTEM_PROMPT,
  DONGYANZHEN_SYSTEM_PROMPT, LINYUHUI_SYSTEM_PROMPT, LIUYAO_SYSTEM_PROMPT,
  CONGBIN_SYSTEM_PROMPT, JIAZHIWEN_SYSTEM_PROMPT, ZHANGJIZONG_SYSTEM_PROMPT,
  LIULIANG_SYSTEM_PROMPT, LVDENZHONG_SYSTEM_PROMPT, XULIMIN_SYSTEM_PROMPT,
  JIZONGTANG_SYSTEM_PROMPT, CHENGRUI_SYSTEM_PROMPT, WANGQINGJU_SYSTEM_PROMPT,
  MENGXIAOPING_SYSTEM_PROMPT, LIUSHUQUAN_SYSTEM_PROMPT, QIANGHUI_SYSTEM_PROMPT,
  LINQING_SYSTEM_PROMPT, KOUJIANPING_SYSTEM_PROMPT, YUXINMIN_SYSTEM_PROMPT,
  YANZIZHONG_SYSTEM_PROMPT, BAISHAOKANG_SYSTEM_PROMPT, WANGGUIQIANG_SYSTEM_PROMPT,
  MINJIANXIONG_SYSTEM_PROMPT, LIUJIANJUN_SYSTEM_PROMPT, BANMAOSEN_SYSTEM_PROMPT,
  WANGSHIQING_SYSTEM_PROMPT, ZHANGSHAOQING_SYSTEM_PROMPT, WANGYANJI_SYSTEM_PROMPT,
  ZHOUYUNBIAO_SYSTEM_PROMPT, CHENLIN_SYSTEM_PROMPT, GAOZHANGUO_SYSTEM_PROMPT,
  WANLIHUA_SYSTEM_PROMPT,
} from './chinese-experts';

/* 21世纪全球专家 */
import {
  REICHS_SYSTEM_PROMPT, KAYSER_SYSTEM_PROMPT, THALI_SYSTEM_PROMPT,
  BYARD_SYSTEM_PROMPT, UBELAKER_SYSTEM_PROMPT, ASCHHEIM_SYSTEM_PROMPT, ACHARYA_SYSTEM_PROMPT,
  DOUGLAS_SYSTEM_PROMPT, ROSSMO_SYSTEM_PROMPT, BURGESS_SYSTEM_PROMPT,
  HOLES_SYSTEM_PROMPT, DELISI_SYSTEM_PROMPT, RAINE_SYSTEM_PROMPT,
  KWONILYONG_SYSTEM_PROMPT, LEEJINSUK_SYSTEM_PROMPT,
  SHERMAN_SYSTEM_PROMPT, OCONNELL_M_SYSTEM_PROMPT, LEBLANC_SYSTEM_PROMPT,
  SELLA_SYSTEM_PROMPT, KHAN_SYSTEM_PROMPT, BLUMENTHAL_SYSTEM_PROMPT,
  WEISBURD_SYSTEM_PROMPT, BULL_SYSTEM_PROMPT, HAGAN_SYSTEM_PROMPT,
  POLLANEN_SYSTEM_PROMPT, ECKERT_SYSTEM_PROMPT,
  KROLL_SYSTEM_PROMPT, JOSEPH_SYSTEM_PROMPT, ZHANGYUFEN_SYSTEM_PROMPT,
  MCNAMARA_SYSTEM_PROMPT, JENSEN_SYSTEM_PROMPT, WEIHUA_SYSTEM_PROMPT,
  DAVIES_SYSTEM_PROMPT, LEOPOLD_SYSTEM_PROMPT,
  ABBAKYARI_SYSTEM_PROMPT, RASHIDALGHAFRI_SYSTEM_PROMPT, HADIALGHAFRI_SYSTEM_PROMPT,
  RAMANUJGHOSH_SYSTEM_PROMPT, JOHNKAI_SYSTEM_PROMPT,
} from './c21-experts';
export {
  REICHS_SYSTEM_PROMPT, KAYSER_SYSTEM_PROMPT, THALI_SYSTEM_PROMPT,
  BYARD_SYSTEM_PROMPT, UBELAKER_SYSTEM_PROMPT, ASCHHEIM_SYSTEM_PROMPT, ACHARYA_SYSTEM_PROMPT,
  DOUGLAS_SYSTEM_PROMPT, ROSSMO_SYSTEM_PROMPT, BURGESS_SYSTEM_PROMPT,
  HOLES_SYSTEM_PROMPT, DELISI_SYSTEM_PROMPT, RAINE_SYSTEM_PROMPT,
  KWONILYONG_SYSTEM_PROMPT, LEEJINSUK_SYSTEM_PROMPT,
  SHERMAN_SYSTEM_PROMPT, OCONNELL_M_SYSTEM_PROMPT, LEBLANC_SYSTEM_PROMPT,
  SELLA_SYSTEM_PROMPT, KHAN_SYSTEM_PROMPT, BLUMENTHAL_SYSTEM_PROMPT,
  WEISBURD_SYSTEM_PROMPT, BULL_SYSTEM_PROMPT, HAGAN_SYSTEM_PROMPT,
  POLLANEN_SYSTEM_PROMPT, ECKERT_SYSTEM_PROMPT,
  KROLL_SYSTEM_PROMPT, JOSEPH_SYSTEM_PROMPT, ZHANGYUFEN_SYSTEM_PROMPT,
  MCNAMARA_SYSTEM_PROMPT, JENSEN_SYSTEM_PROMPT, WEIHUA_SYSTEM_PROMPT,
  DAVIES_SYSTEM_PROMPT, LEOPOLD_SYSTEM_PROMPT,
  ABBAKYARI_SYSTEM_PROMPT, RASHIDALGHAFRI_SYSTEM_PROMPT, HADIALGHAFRI_SYSTEM_PROMPT,
  RAMANUJGHOSH_SYSTEM_PROMPT, JOHNKAI_SYSTEM_PROMPT,
} from './c21-experts';

/** 侦探系统提示词注册表 */
export const SYSTEM_PROMPTS: Record<DetectiveId, string> = {
  holmes: HOLMES_SYSTEM_PROMPT,
  conan: CONAN_SYSTEM_PROMPT,
  digong: DIGONG_SYSTEM_PROMPT,
  baozheng: BAOZHENG_SYSTEM_PROMPT,
  songci: SONGCI_SYSTEM_PROMPT,
  hairui: HAIRUI_SYSTEM_PROMPT,
  kuangzhong: KUANGZHONG_SYSTEM_PROMPT,
  shishilun: SHISHILUN_SYSTEM_PROMPT,
  gaoyao: GAOTAO_SYSTEM_PROMPT,
  zhaoguanghan: ZHAOGUANGHAN_SYSTEM_PROMPT,
  huangba: HUANGBA_SYSTEM_PROMPT,
  kouzhun: KOUZHUN_SYSTEM_PROMPT,
  yuchenglong: YUCHENGLONG_SYSTEM_PROMPT,
  xuyougong: XUYOUGONG_SYSTEM_PROMPT,
  cicero: CICERO_SYSTEM_PROMPT,
  antiphon: ANTIPHON_SYSTEM_PROMPT,
  chanakya: CHANAKYA_SYSTEM_PROMPT,
  qehsu: QEHSU_SYSTEM_PROMPT,
  lareynie: LAREYNIE_SYSTEM_PROMPT,
  desgrez: DESGREZ_SYSTEM_PROMPT,
  hfielding: HFIELDING_SYSTEM_PROMPT,
  jfielding: JFIELDING_SYSTEM_PROMPT,
  vidocq: VIDOCQ_SYSTEM_PROMPT,
  bertillon: BERTILLON_SYSTEM_PROMPT,
  abberline: ABERLINE_SYSTEM_PROMPT,
  gross: GROSS_SYSTEM_PROMPT,
  locard: LOCARD_SYSTEM_PROMPT,
  bell: BELL_SYSTEM_PROMPT,
  galton: GALTON_SYSTEM_PROMPT,
  caminada: CAMINADA_SYSTEM_PROMPT,
  wensley: WENSLEY_SYSTEM_PROMPT,
  clarke: CLARKE_SYSTEM_PROMPT,
  pollaky: POLLAKY_SYSTEM_PROMPT,
  featherstone: FEATHERSTONE_SYSTEM_PROMPT,
  pinkerton: PINKERTON_SYSTEM_PROMPT,
  warne: WARNE_SYSTEM_PROMPT,
  einstein: EINSTEIN_SYSTEM_PROMPT,
  petrosino: PETROSINO_SYSTEM_PROMPT,
  burns: BURNS_SYSTEM_PROMPT,
  flynn: FLYNN_SYSTEM_PROMPT,
  chaplain: CHAPLAIN_SYSTEM_PROMPT,
  goodwin: GOODWIN_SYSTEM_PROMPT,
  clement: CLEMENT_SYSTEM_PROMPT,
  west: WEST_SYSTEM_PROMPT,
  mallory: MALLORY_SYSTEM_PROMPT,
  webster: WEBSTER_SYSTEM_PROMPT,
  schindler: SCHINDLER_SYSTEM_PROMPT,
  oconnell_j: OCONNELL_J_SYSTEM_PROMPT,
  oconnell_d: OCONNELL_D_SYSTEM_PROMPT,
  spilsbury: SPILSBURY_SYSTEM_PROMPT,
  henrylee: HENRYLEE_SYSTEM_PROMPT,
  ness: NESS_SYSTEM_PROMPT,
  jeffreys: JEFFREYS_SYSTEM_PROMPT,
  glessnerlee: GLESSNERLEE_SYSTEM_PROMPT,
  toschi: TOSCHI_SYSTEM_PROMPT,
  kenda: KENDA_SYSTEM_PROMPT,
  pistone: PISTONE_SYSTEM_PROMPT,
  murphy: MURPHY_SYSTEM_PROMPT,
  pena: PENA_SYSTEM_PROMPT,
  serpico: SERPICO_SYSTEM_PROMPT,
  hiratsuka: HIRATSUKA_SYSTEM_PROMPT,
  koshko: KOSHKO_SYSTEM_PROMPT,
  tofte: TOFTE_SYSTEM_PROMPT,
  fabian: FABIAN_SYSTEM_PROMPT,
  wickstead: WICKSTEAD_SYSTEM_PROMPT,
  murray: MURRAY_SYSTEM_PROMPT,
  tallman: TALLMAN_SYSTEM_PROMPT,
  christie: CHRISTIE_SYSTEM_PROMPT,
  onraet: ONRAET_SYSTEM_PROMPT,
  wuguoqing: WUGUOQING_SYSTEM_PROMPT,
  cuidaozhi: CUIDAOZHI_SYSTEM_PROMPT,
  chenshixian: CHENSHIXIAN_SYSTEM_PROMPT,
  gaotangdou: GAOTANGDOU_SYSTEM_PROMPT,
  zhangxin: ZHANGXIN_SYSTEM_PROMPT,
  mayulin: MAYULIN_SYSTEM_PROMPT,
  dongyanzhen: DONGYANZHEN_SYSTEM_PROMPT,
  linyuhui: LINYUHUI_SYSTEM_PROMPT,
  liuyao: LIUYAO_SYSTEM_PROMPT,
  congbin: CONGBIN_SYSTEM_PROMPT,
  jiazhiwen: JIAZHIWEN_SYSTEM_PROMPT,
  zhangjizong: ZHANGJIZONG_SYSTEM_PROMPT,
  liuliang: LIULIANG_SYSTEM_PROMPT,
  lvdenzhong: LVDENZHONG_SYSTEM_PROMPT,
  xulimin: XULIMIN_SYSTEM_PROMPT,
  jizongtang: JIZONGTANG_SYSTEM_PROMPT,
  chengrui: CHENGRUI_SYSTEM_PROMPT,
  wangqingju: WANGQINGJU_SYSTEM_PROMPT,
  mengxiaoping: MENGXIAOPING_SYSTEM_PROMPT,
  liushuquan: LIUSHUQUAN_SYSTEM_PROMPT,
  qianghui: QIANGHUI_SYSTEM_PROMPT,
  linqing: LINQING_SYSTEM_PROMPT,
  koujianping: KOUJIANPING_SYSTEM_PROMPT,
  yuxinmin: YUXINMIN_SYSTEM_PROMPT,
  yanzizhong: YANZIZHONG_SYSTEM_PROMPT,
  baishaokang: BAISHAOKANG_SYSTEM_PROMPT,
  wangguiqiang: WANGGUIQIANG_SYSTEM_PROMPT,
  minjianxiong: MINJIANXIONG_SYSTEM_PROMPT,
  liujianjun: LIUJIANJUN_SYSTEM_PROMPT,
  banmaosen: BANMAOSEN_SYSTEM_PROMPT,
  wangshiqing: WANGSHIQING_SYSTEM_PROMPT,
  zhangshaoqing: ZHANGSHAOQING_SYSTEM_PROMPT,
  wangyanji: WANGYANJI_SYSTEM_PROMPT,
  zhouyunbiao: ZHOUYUNBIAO_SYSTEM_PROMPT,
  chenlin: CHENLIN_SYSTEM_PROMPT,
  gaozhanguo: GAOZHANGUO_SYSTEM_PROMPT,
  wanlihua: WANLIHUA_SYSTEM_PROMPT,
  reichs: REICHS_SYSTEM_PROMPT,
  kayser: KAYSER_SYSTEM_PROMPT,
  thali: THALI_SYSTEM_PROMPT,
  byard: BYARD_SYSTEM_PROMPT,
  ubelaker: UBELAKER_SYSTEM_PROMPT,
  aschheim: ASCHHEIM_SYSTEM_PROMPT,
  acharya: ACHARYA_SYSTEM_PROMPT,
  douglas: DOUGLAS_SYSTEM_PROMPT,
  rossmo: ROSSMO_SYSTEM_PROMPT,
  burgess: BURGESS_SYSTEM_PROMPT,
  holes: HOLES_SYSTEM_PROMPT,
  delisi: DELISI_SYSTEM_PROMPT,
  raine: RAINE_SYSTEM_PROMPT,
  kwonilyong: KWONILYONG_SYSTEM_PROMPT,
  leejinsuk: LEEJINSUK_SYSTEM_PROMPT,
  sherman: SHERMAN_SYSTEM_PROMPT,
  oconnell_m: OCONNELL_M_SYSTEM_PROMPT,
  leblanc: LEBLANC_SYSTEM_PROMPT,
  sella: SELLA_SYSTEM_PROMPT,
  khan: KHAN_SYSTEM_PROMPT,
  blumenthal: BLUMENTHAL_SYSTEM_PROMPT,
  weisburd: WEISBURD_SYSTEM_PROMPT,
  bull: BULL_SYSTEM_PROMPT,
  hagan: HAGAN_SYSTEM_PROMPT,
  pollanen: POLLANEN_SYSTEM_PROMPT,
  eckert: ECKERT_SYSTEM_PROMPT,
  kroll: KROLL_SYSTEM_PROMPT,
  joseph: JOSEPH_SYSTEM_PROMPT,
  zhangyufen: ZHANGYUFEN_SYSTEM_PROMPT,
  mcnamara: MCNAMARA_SYSTEM_PROMPT,
  jensen: JENSEN_SYSTEM_PROMPT,
  weihua: WEIHUA_SYSTEM_PROMPT,
  davies: DAVIES_SYSTEM_PROMPT,
  leopold: LEOPOLD_SYSTEM_PROMPT,
  abbakyari: ABBAKYARI_SYSTEM_PROMPT,
  rashidalghafri: RASHIDALGHAFRI_SYSTEM_PROMPT,
  hadialghafli: HADIALGHAFRI_SYSTEM_PROMPT,
  ramanujghosh: RAMANUJGHOSH_SYSTEM_PROMPT,
  johnkai: JOHNKAI_SYSTEM_PROMPT,
};

export function getSystemPrompt(detectiveId: DetectiveId): string {
  return SYSTEM_PROMPTS[detectiveId];
}
